swagger: "2.0"
info:
  version: "1.0.0"
  title: "Library System API"
  description: "API for managing library system"
host: "localhost:3000"
basePath: "/"
schemes:
  - "http"
paths:
  /members:
    get:
      summary: "Get all members"
      description: "Returns a list of all members"
      responses:
        200:
          description: "A list of members"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Member"
  /members/{code}:
    get:
      summary: "Get a member by code"
      description: "Returns a single member"
      parameters:
        - name: "code"
          in: "path"
          required: true
          type: "string"
      responses:
        200:
          description: "A single member"
          schema:
            $ref: "#/definitions/Member"
    post:
      summary: "Create a new member"
      description: "Creates a new member"
      parameters:
        - in: "body"
          name: "body"
          description: "Member object that needs to be added"
          required: true
          schema:
            $ref: "#/definitions/Member"
      responses:
        201:
          description: "Member created"
    put:
      summary: "Update a member"
      description: "Updates an existing member"
      parameters:
        - name: "code"
          in: "path"
          required: true
          type: "string"
        - in: "body"
          name: "body"
          description: "Member object that needs to be updated"
          required: true
          schema:
            $ref: "#/definitions/Member"
      responses:
        200:
          description: "Member updated"
    delete:
      summary: "Delete a member"
      description: "Deletes an existing member"
      parameters:
        - name: "code"
          in: "path"
          required: true
          type: "string"
      responses:
        200:
          description: "Member deleted"
  /members/{memberId}/borrow/{bookId}:
    post:
      summary: "Borrow a book"
      description: "Allows a member to borrow a book"
      parameters:
        - name: "memberId"
          in: "path"
          required: true
          type: "string"
        - name: "bookId"
          in: "path"
          required: true
          type: "string"
      responses:
        200:
          description: "Book borrowed"
  /members/{memberId}/return/{bookId}:
    post:
      summary: "Return a book"
      description: "Allows a member to return a book"
      parameters:
        - name: "memberId"
          in: "path"
          required: true
          type: "string"
        - name: "bookId"
          in: "path"
          required: true
          type: "string"
      responses:
        200:
          description: "Book returned"
  /books:
    get:
      summary: "Get all books"
      description: "Returns a list of all books"
      responses:
        200:
          description: "A list of books"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Book"
  /books/{code}:
    get:
      summary: "Get a book by code"
      description: "Returns a single book"
      parameters:
        - name: "code"
          in: "path"
          required: true
          type: "string"
      responses:
        200:
          description: "A single book"
          schema:
            $ref: "#/definitions/Book"
    post:
      summary: "Create a new book"
      description: "Creates a new book"
      parameters:
        - in: "body"
          name: "body"
          description: "Book object that needs to be added"
          required: true
          schema:
            $ref: "#/definitions/Book"
      responses:
        201:
          description: "Book created"
    put:
      summary: "Update a book"
      description: "Updates an existing book"
      parameters:
        - name: "code"
          in: "path"
          required: true
          type: "string"
        - in: "body"
          name: "body"
          description: "Book object that needs to be updated"
          required: true
          schema:
            $ref: "#/definitions/Book"
      responses:
        200:
          description: "Book updated"
    delete:
      summary: "Delete a book"
      description: "Deletes an existing book"
      parameters:
        - name: "code"
          in: "path"
          required: true
          type: "string"
      responses:
        200:
          description: "Book deleted"
definitions:
  Member:
    type: "object"
    required:
      - "code"
      - "name"
    properties:
      code:
        type: "string"
      name:
        type: "string"
  Book:
    type: "object"
    required:
      - "code"
      - "title"
      - "author"
      - "stock"
    properties:
      code:
        type: "string"
      title:
        type: "string"
      author:
        type: "string"
      stock:
        type: "integer"
